locale:
  languageTag: en_US
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/presentation?serverTimezone=UTC
    username: postgres
    password: postgres
    hikari:
      connection-test-query: 'SELECT 1'
  profiles:
    active: dev
  liquibase:
    change-log: classpath:/db/master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: true
  servlet:
    multipart:
      maxFileSize: 5MB
      max-request-size: 5MB
  mail:
    default-encoding: UTF-8